import { DataTypes, Model, Optional } from "sequelize";
import { sequelize } from "../../../config";  // Ensure this points to your sequelize instance

// Define a TypeScript interface for the attributes of the transaction model
interface TransactionAttributes {
    transactionId: string;
    description: string | null;
    entity: string;
    status: string | null;
    amount: number | null;
    currency: string | null;
    failureReason: string | null;
    createdAt: Date;
    updatedAt: Date;
    deletedAt?: Date; // Paranoid deletes (optional)
}

// Create a TypeScript interface for the optional attributes during creation (for inserts)
interface TransactionCreationAttributes extends Optional<TransactionAttributes, "createdAt" | "updatedAt" | "deletedAt"> {
}

class TransactionModel extends Model<TransactionAttributes, TransactionCreationAttributes> implements TransactionAttributes {
    transactionId!: string;
    description!: string | null;
    entity!: string;
    status!: string | null;
    amount!: number | null;
    currency!: string | null;
    failureReason!: string | null;
    createdAt!: Date;
    updatedAt!: Date;
    deletedAt?: Date | null; // Optional, only present if paranoid is enabled
}

// Initialize the Sequelize model
TransactionModel.init(
    {
        transactionId: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: true, // Ensure that transactionId is unique
        },
        description: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        entity: {
            type: DataTypes.STRING,
            allowNull: false,
        },
        status: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        amount: {
            type: DataTypes.INTEGER, // Store amounts as integers (e.g., cents)
            allowNull: true,
        },
        currency: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        failureReason: {
            type: DataTypes.STRING,
            allowNull: true,
        },
        createdAt: {
            type: DataTypes.DATE,
        },
        updatedAt: {
            type: DataTypes.DATE,
            allowNull: true,
        },
    },
    {
        sequelize,  // Sequelize instance
        tableName: "transactions",  // Name of the table in the database
        timestamps: true,  // Sequelize will automatically handle createdAt and updatedAt
        paranoid: true,  // Soft delete support (if needed)
        // `id` is automatically generated by PostgreSQL because it's the default primary key
    },
);

export { TransactionModel };
