import { DataTypes, Model, Optional } from 'sequelize';
import { sequelize } from "../../../config";
import { FranchiseeAttributes, FranchiseeLocation, FranchiseType } from '../../../interfaces';

// Franchisee creation attributes, making 'id' optional for creation
interface FranchiseeCreationAttributes extends Optional<FranchiseeAttributes, 'id'> { }

// Franchisee class model for the Sequelize ORM
class FranchiseeModel extends Model<FranchiseeAttributes, FranchiseeCreationAttributes> implements FranchiseeAttributes {
  public id!: string;
  public userid?: string;
  public referBy?: string;
  public name!: string;
  public ownerName!: string;
  public contactEmail!: string;
  public contactNumber!: string;
  public franchiseLocations?: FranchiseeLocation[];
  public establishedDate!: Date;
  public franchiseAgreementSignedDate!: Date;
  public franchiseType!: FranchiseType;
  public region!: string;
  public description!: string;
  public website!: string;
  public socialMediaLinks!: string[];
  public logo!: string;
  public numberOfEmployees!: number;
  public investmentAmount!: number;
  public royaltyPercentage!: number;
  public monthlyRevenue!: number;
  public numberOfOutlets!: number;
  public menuSpecialty!: string;
  public businessHours!: string;
  public deliveryOptions!: boolean;
  public isActive!: boolean;
  public ratings!: number;
  public promotions!: string[];
  public targetMarket!: string;
  public sustainabilityPractices!: string;
  public trainingPrograms!: string[];
  public supportContact?: string;
  public operationalChallenges!: string[];
  public competitiveAdvantages!: string;
  public expansionPlans!: string;
  public customerFeedback!: string[];
  public industryCertifications!: string[];
  public affiliatePrograms!: string[];
  public performanceMetrics!: { [key: string]: number };
  public franchiseRenewalInfo!: { renewalDate: Date; conditions: string } | null;
  public partnerships!: string[];
  public marketingStrategies!: string[];
  public trainingHistory!: { date: Date; topic: string }[];
  public crisisManagementPlans!: string;
  public diversityInitiatives!: string;
}

// Initializing the model and its schema
FranchiseeModel.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    userid: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    referBy: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      comment: "Name of the franchisee",
    },
    ownerName: {
      type: DataTypes.STRING,
      allowNull: false,
      comment: "Name of the owner or primary contact",
    },
    contactEmail: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    contactNumber: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Primary contact number for the franchisee",
    },
    franchiseLocations: {
      type: DataTypes.ARRAY(DataTypes.JSONB),
      allowNull: false,
      comment: "Locations of the franchise outlets",
    },
    establishedDate: {
      type: DataTypes.DATE,
      allowNull: false,
      comment: "Date when the franchise was established",
    },
    franchiseAgreementSignedDate: {
      type: DataTypes.DATE,
      allowNull: false,
      comment: "Date when the franchise agreement was signed",
    },
    franchiseType: {
      type: DataTypes.ENUM(...Object.values(FranchiseType)),
      allowNull: false,
    },
    region: {
      type: DataTypes.STRING,
      allowNull: false,
      comment: "Geographical region of operation for the franchisee",
    },
    description: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Detailed description of the franchisee's business model",
    },
    website: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Website URL for the franchisee",
    },
    socialMediaLinks: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true,
      comment: "Links to social media profiles associated with the franchisee",
    },
    logo: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "URL to the franchisee's logo",
    },
    numberOfEmployees: {
      type: DataTypes.INTEGER,
      allowNull: false,
      comment: "Total number of employees working under the franchisee",
    },
    investmentAmount: {
      type: DataTypes.DECIMAL(10, 2),
      allowNull: false,
      comment: "Initial investment amount required to establish the franchise",
    },
    royaltyPercentage: {
      type: DataTypes.DECIMAL(5, 2),
      allowNull: false,
      comment: "Percentage of revenue paid to the franchisor as royalties",
    },
    monthlyRevenue: {
      type: DataTypes.DECIMAL(10, 2),
      allowNull: false,
      comment: "Average monthly revenue generated by the franchisee",
    },
    numberOfOutlets: {
      type: DataTypes.INTEGER,
      allowNull: false,
      comment: "Total number of outlets owned by the franchisee",
    },
    menuSpecialty: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Specialty items or unique offerings on the franchise menu",
    },
    businessHours: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Operating hours for the franchise outlets",
    },
    deliveryOptions: {
      type: DataTypes.BOOLEAN,
      allowNull: true,
      comment: "Indicates whether the franchisee offers delivery options",
    },
    isActive: {
      type: DataTypes.BOOLEAN,
      defaultValue: true,
      comment: "Indicates if the franchisee is currently active or not",
    },
    ratings: {
      type: DataTypes.FLOAT,
      allowNull: true,
      comment: "Average rating for the franchisee based on customer reviews",
    },
    promotions: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true,
      comment: "Current promotions or special offers available at the franchise",
    },
    targetMarket: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Description of the target market demographics and preferences",
    },
    sustainabilityPractices: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Description of sustainability practices implemented by the franchisee",
    },
    trainingPrograms: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true,
      comment: "List of training programs available for franchise staff",
    },
    supportContact: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Contact information for customer or franchisee support",
    },
    operationalChallenges: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true,
      comment: "Common operational challenges faced by the franchisee",
    },
    competitiveAdvantages: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Unique competitive advantages the franchisee has in the market",
    },
    expansionPlans: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Plans or strategies for future growth and expansion of the franchise",
    },
    customerFeedback: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true,
      comment: "Feedback and testimonials from customers of the franchisee",
    },
    industryCertifications: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true,
      comment: "Relevant industry certifications, awards, or recognitions received",
    },
    affiliatePrograms: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true,
      comment: "Details about affiliate programs the franchisee participates in",
    },
    performanceMetrics: {
      type: DataTypes.JSONB,
      allowNull: true,
      comment: "Metrics used to evaluate franchise performance (e.g., sales, satisfaction)",
    },
    franchiseRenewalInfo: {
      type: DataTypes.JSONB,
      allowNull: true,
      comment: "Information regarding franchise renewal terms and conditions",
    },
    partnerships: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true,
      comment: "Details on partnerships with suppliers, vendors, or other organizations",
    },
    marketingStrategies: {
      type: DataTypes.ARRAY(DataTypes.STRING),
      allowNull: true,
      comment: "Marketing strategies employed by the franchisee and their effectiveness",
    },
    trainingHistory: {
      type: DataTypes.ARRAY(DataTypes.JSONB),
      allowNull: true,
      comment: "Record of training sessions attended by staff",
    },
    crisisManagementPlans: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Plans for handling emergencies or crises effectively",
    },
    diversityInitiatives: {
      type: DataTypes.STRING,
      allowNull: true,
      comment: "Efforts towards diversity and inclusion in hiring and operations",
    },
  },
  {
    sequelize,
    tableName: 'franchisees',
    timestamps: true,
  }
);

export { FranchiseeModel };
