name: Deploy to EC2 via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run deployment command on EC2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Environment,Values=Production" \
            --parameters 'commands=["cd /home/ubuntu/tongue-tinglers/Tongue-Tinglers-Backend", "git pull origin main", "pnpm install", "npm run build", "pm2 restart all"]' \
            --comment "Deploying application from GitHub Actions" \
            --timeout-seconds 600 \
            --max-concurrency "1" \
            --max-errors "0"
